language: java
jdk: oraclejdk8
after_success:
- ./upload.sh
before_install:
- openssl aes-256-cbc -K $encrypted_2fafd8f03c70_key -iv $encrypted_2fafd8f03c70_iv
  -in secring.gpg.enc -out secring.gpg -d
