language: java
jdk: oraclejdk8
after_success:
- ./upload.sh
before_install:
- '[ "$TRAVIS_PULL_REQUEST" == "false" ] && openssl aes-256-cbc -K $encrypted_2fafd8f03c70_key -iv $encrypted_2fafd8f03c70_iv -in secring.gpg.enc -out secring.gpg -d || echo "no decryption for pull requests"'